---
# tasks file for firewall

- name: Open some firewall ports
  sudo: yes
  firewalld:
    port: "{{ item.port }}"
    permanent: yes
    state: enabled
    immediate: yes
    zone: public
  with_items: firewalld_allow
  when: firewalld_allow is defined

- name: Close some firewall ports
  sudo: yes
  firewalld:
    port: "{{ item.port }}"
    permanent: yes
    state: enabled
    immediate: yes
    zone: public
  with_items: firewalld_deny
  when: firewalld_deny is defined
