---
# tasks file for firewall

- name: Open some firewall ports
  ufw:
    rule: "allow"
    port: "{{ item.port }}"
    proto: "{{ item.proto | default('tcp') }}"
    state: reloaded
  with_items: firewall_allow
  when: firewall_allow is defined

- name: Close some firewall ports
  ufw:
    rule: "deny"
    port: "{{ item.port }}"
    proto: "{{ item.proto | default('tcp') }}"
    state: reloaded
  with_items: firewall_deny
  when: firewall_deny is defined
